name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AndreiLobanovich/labeler@fix_no_yml_file_error_message
        with:
          configuration-path: ./labeler.yml
