name: "Conditional run"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - id: label-the-PR
      uses: danielsht86/labeler@danielsht86/add-outputs
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - id: run-frontend-tests
      if: contains(fromJson(steps.label-the-PR.outputs.all-labels), 'frontend')
      run: |
        echo "Running frontend tests..."
        # Put your commands for running frontend tests here
  
    - id: run-backend-tests
      if: contains(fromJson(steps.label-the-PR.outputs.all-labels), 'backend')
      run: |
        echo "Running backend tests..."
        # Put your commands for running backend tests here
