name: createPR
on: dispatch
jobs:
  createPR:
    steps:
      - uses: peter-evans/create-pull-request@v5
      with:
        commit-message: test
        title: test
        body: test
        branch: test
