name: 'createPR'
on: workflow_dispatch
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'test'
          title: 'test'
          body: 'test'
          branch: 'test'
