name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update README.md
        run: echo '*' >> README.md

      - id: cr-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update README.md'
          title: 'Update README.md'
          body: 'Appended * to the end of README.md'
          branch: 'update-readme'
      
      - name: testEcho
        run: echo ${{steps.cr-pr.outputs.pr_number}}
        
      - name: Label Pull Request
        uses: credfeto/labeler@feature/pass-in-pull-request-or-issue
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
          pr-number: ${{steps.cr-pr.outputs.pull-request-number}}
