name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kachkaev/labeler@dot-option
        with:
          configuration-path: .github/labeler.yml
          dot: true
    
