name: Labeler
on: pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - uses: credfeto/labeler@feature/pass-in-pull-request-or-issue
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        dot: true
        pr-number: 999
