name: Labeler
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: jsoref/labeler@fix-labeler
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        dot: true
